---
version: '3'
services:
  kernel_builder:
    build: ./build
    image: neofob/kernel_builder:latest
    container_name: kernel_builder
    hostname: kernel_builder
    volumes:
      - ${KERNEL_SRC}:/src/linux:ro
      - ${BUILD_OUTPUT}:/build_output
      - ${OLD_CONFIG}:/old_config:ro
      - /etc/passwd:/etc/passwd:ro
      - ./scripts/build_kernel.sh:/entrypoint.sh
    # this is the 1st user in Debian/Ubuntu
    user: "1000:1000"
    entrypoint:
      - /entrypoint.sh
